### ISSUE TITLE
Pre-built packages for Polymer Platinum Elements

### ISSUE THREAD

**Issue by matoorn** [vaadin/gwt-api-generator#39]
Support as a pre-built package for Polymer Platinum Elements, specially the Service worker platinum-sw.

**Comment by manolo** [comment]
We are planning to add this, but we need some time to prepare the demos and test the generated code.

In the meanwhile you could use the components in your java project following these instructions:

```
   $ npm install gwt-api-generator -g  (or $ sudo npm install gwt-api-generator -g) 
   $ bower install PolymerElements/platinum-elements
   $ gwt-api-generator --excludeLib
```

After that you will have all the needed classes under `src/main/java/com/vaadin/polymer/platinum`

**Comment by manolo** [comment]
Fixed. Please use gwt-polymer-elements 1.7.0.0-SNAPSHOT until 1.7.0.0 is released
