### ISSUE TITLE
compilation failure

### ISSUE THREAD

**Issue by j-mi-jim** [vaadin/gwt-api-generator#58]
Since today, i've some errors while compiling
because package com.google.gwt.core.client.js does not exist anymore.

**Comment by manolo** [comment]
Thanks for the heads up

**Comment by manolo** [comment]
jsinterop legacy support was just removed https://github.com/gwtproject/gwt/commit/dd141d676eee3c2fcf20ac0ab715c62a1d07e213

Let's follow this in #54

**Comment by manolo** [comment]
Updated gwt-polymer-elements-1.2.3.0-SNAPSHOT in maven repos, try it,  and your project should compile.

**Comment by j-mi-jim** [comment]
I confirm, no problems anymore. thank you very much.
