### ISSUE TITLE
Generated vaadin-grid can't seem to utilize getItem

### ISSUE THREAD

**Issue by cpboyd** [vaadin/gwt-api-generator#61]
Example code:
```
// Load 
grid.getPolymerElement().addEventListener(SelectedItemsChangedEvent.NAME, event -> {
    JsArrayNumber n = grid.getSelection().selected(null, 0, 200).cast();
    if (n.length() == 1) {
        grid.getItem(n.get(0), new Function<JavaScriptObject, Object>() {
            @Override
            public JavaScriptObject call(Object arg) {
                main.load(arg);
                return null;
            }
        }, false);
    }
});
```
The Object arg always seems to be null, regardless of which row is selected.

The issue seems to be that getItem() should take a function with two inputs (JSFunction2 in vaadin-grid's gwt code).
```function (error, item) {}```

Perhaps arg is simply the "error" input?  (Which would make sense, as it should be null.)

There's not currently any way to easily get a specific row's data via the generated code.

**Comment by cpboyd** [comment]
It's not a huge issue in this particular case, since I'm keeping a copy of the item list in GWT and can just pull from there.

However, it could pose issues if there's other JS functions that take callback functions with more than one argument as parameters.

**Comment by manolo** [comment]
It's almost impossible to figure out the arguments of a callback. Hydrolysis does not provide that info. Also we would need to define a hight amount of functional interfaces for all possibilities.

But because we are using the JsInterop `@JsFunction`, we can cast and your code would be this:

```
// Define the function which matches the JS signature
@JsFunction
 public interface Function2 {
     void call(Object a, Object b);
 }
// Cast it in the method call
grid.getPolymerElement().addEventListener(SelectedItemsChangedEvent.NAME, event -> {
    JsArrayNumber n = grid.getSelection().selected(null, 0, 200).cast();
     if (n.length() == 1) {
        grid.getItem(n.get(0), (Function)callback, false);
     }
});        
```

**Comment by cpboyd** [comment]
Ah, ok.  That works!

Thanks!
