### ISSUE TITLE
Events do not support @UiHandler simple binding

### ISSUE THREAD

**Issue by cpboyd** [vaadin/gwt-api-generator#62]
Reference: http://www.gwtproject.org/doc/latest/DevGuideUiBinder.html#Simple_binding

The generated Events do not extend GwtEvent, so the simple binding does not work.

**Comment by muelbr** [comment]
I am currently not able to generate the API but my version from a month ago has to packages for events:

1. For widgets: com.vaadin.polymer.iron.widget.event.*
2. For elements: com.vaadin.polymer.iron.event.*

The first one extends `DomEvent<H> / GwtEvent<H>` and works with the `@UiHandler`-Annotation. The second one is for pure elements and works with `addEventListener(event, handler)`

Are you sure that you have choosen the right one...?

**Comment by cpboyd** [comment]
Ah, I see.

My mistake; I must've been using the elements one.
