### ISSUE TITLE
Not valid Java code for events.

### ISSUE THREAD

**Issue by frami** [vaadin/gwt-api-generator#64]
With the gwt-api-generator I generated the source for PolymerElements:
gwt-api-generator --package=PolymerElements/paper-elements

After generating I tryied to compile it, but there was on some parts not valid Java code generaded. For example in the class IronOverlayClosedEvent.java on line 37:

@JsProperty JavaScriptObject getEvent.detail();

**Comment by manolo** [comment]
Fixed in ecb419c
