### ISSUE TITLE
Ambiguous 'setSelected' on PaperMenu / PaperTabs / PaperListbox / PaperRadioGroup

### ISSUE THREAD

**Issue by muelbr** [vaadin/gwt-api-generator#66]
The signature for the getter / setter of `selected` has been changed from `String `to `Object`
But there ist still a method `setSelected(String)` doing
`getPolymerElement().setAttribute("selected", value);`
instead of
`getPolymerElement().setSelected(value);`

This can cause wrong behave if the menu should have no selection with:
`setSelected(null)`

**Comment by cpboyd** [comment]
Ultimately, this has to do with how the Java setters are generated.

See the Widget template, line 78:
https://github.com/vaadin/gwt-api-generator/blob/master/template/Widget.template#L78
