### ISSUE TITLE
Widget.template should import Polymer

### ISSUE THREAD

**Issue by cpboyd** [vaadin/gwt-api-generator#69]
[Line 79 of Widget.template](https://github.com/vaadin/gwt-api-generator/blob/master/template/Widget.template#L79) makes use of `Polymer.property()` but there's no `import com.vaadin.polymer.Polymer;`

**Comment by halkosajtarevic** [comment]
+1

**Comment by manolo** [comment]
fixed in f9abb4d82c01e0ccea64d90c6ab3eb14e29f7471
