### ISSUE TITLE
Polymer#saveProperties ruins Vaadin's connectorId handling

### ISSUE THREAD

**Issue by attilapuskas** [vaadin/gwt-api-generator#70]
In Vaadin the _tkPid_ is used to store the connectorId on an element but this has been removed when the saveProperties method is called. If a layout phase is in progress around these elements then Vaadin is not able to retrieve the corresponding Connector which leads to exceptions.

A possible solution could be that the saveProperties ignores the _tkPid_ as well which is anyway a "final" property.

**Comment by manolo** [comment]
Actually I think that hack is not necessary anymore because polymer already is saving and restoring values set previously to the initialisation. Have to double check though.

**Comment by attilapuskas** [comment]
Would be cool, thanks for the quick reply!
