### ISSUE TITLE
Polymer clears the value of window.performance

### ISSUE THREAD

**Issue by attilapuskas** [vaadin/gwt-api-generator#71]
In the Polymer class the performance field has been introduced:
[here](https://github.com/vaadin/gwt-api-generator/blob/master/lib/com/vaadin/polymer/Polymer.java#L34)
which makes the previously not null performance undefined. This causes an exception for example in iron-list.html where the `window.performance.now()` is called without checking whether the performance has a value or not.

**Comment by frami** [comment]
We have the same problem. We always have to comment out this part of the Polymer class.

**Comment by cpboyd** [comment]
When compiling, I get a possibly related warning:
```
[INFO]       [WARN] Exporting effectively non-final field com.vaadin.polymer.Polymer.performance. Due to the way exporting works, the value of the exported field will not be reflected across Java/JavaScript border.
```

**Comment by manolo** [comment]
Seems introduced by mistake
